# Generated by Django 4.1.4 on 2022-12-11 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.CharField(max_length=1000)),
                ('title', models.CharField(max_length=50)),
                ('tags', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=1000)),
                ('git', models.CharField(max_length=50)),
            ],
        ),
    ]
